### ISSUE TITLE
trajectory selection module

### ISSUE THREAD

**Issue by quyouyuan** [TianhongDai/esil-hindsight#2]
Hello! I'm very interested in your research. I think it's very helpful for me. I saw the trajectory selection module in the paper "Episodic Self-Imitation Learning with Hindsight", but I didn't find it in the code. Would you please help me find out where the code reflects this? I'm very sorry to delay your time due to my ability to understand the code，thanks

**Comment by TianhongDai** [comment]
@quyouyuan Hi, the trajectory selection module in Eq.(10) is in: [https://github.com/TianhongDai/esil-hindsight/blob/main/rl_base/ppo_agent.py#L168](https://github.com/TianhongDai/esil-hindsight/blob/main/rl_base/ppo_agent.py#L168); the calculations of corresponding returns are in: [https://github.com/TianhongDai/esil-hindsight/blob/main/rl_base/ppo_agent.py#L119-L134](https://github.com/TianhongDai/esil-hindsight/blob/main/rl_base/ppo_agent.py#L119-L134).

**Comment by quyouyuan** [comment]
Thank you for your reply
