### ISSUE TITLE
hyperparameter

### ISSUE THREAD

**Issue by quyouyuan** [TianhongDai/esil-hindsight#3]
Hello! It's convenient for you to answer how many hyperparameters are set when you are running? For example, 'cycles','epoch'. I use the parameters given by readme.md, how can I not run out the results of the model you gave me! Thank you for your answer

**Comment by TianhongDai** [comment]
@quyouyuan Hi, all of the parameters I used is in: [https://github.com/TianhongDai/esil-hindsight/blob/main/arguments.py](https://github.com/TianhongDai/esil-hindsight/blob/main/arguments.py). I believe if you use the command that I provide in the `readme.md`, you can definitely reproduce the results. To be noticed, the **number of mpi worker** should be kept the same as the instruction for the corresponding tasks. For `FetchReach` task, you can use 1 mpi worker for quick verification. But for other tasks, please use the number of mpi worker provided in the instructions.

Some tasks using different hyperparameters in `arguments.py` is `FetchPickAndPlace` and `FetchSlide` (I also provide this in the `readme.md`, please check them carefully):

- FetchPickAndPlace
```bash
mpirun -np 32 python train.py --env-name='FetchPickAndPlace-v1' --adaptive-beta --display-interval=1 --batch-size=40 --ncycles=100 --total-frames=5000000
```
- FetchSlide
```bash
mpirun -np 32 python train.py --env-name='FetchSlide-v1' --adaptive-beta --display-interval=1 --batch-size=40 --ncycles=100 --total-frames=5000000
```
 If you have any further questions, please let me know.
